/*
# Add adaptive_plans table to Supabase

## Purpose
Stores the adaptive recommendations generated by the Evorozen Neural Pulse AI engine.
Each row represents one AI-generated study recommendation for a learner.

## New Tables

### adaptive_plans
- `id` (uuid, primary key)
- `plan_id` (uuid, FK → study_plans, cascade delete) — links to the study plan
- `priority_topic` (text, not null) — highest priority topic from Neural Pulse
- `recommended_activity` (text, not null) — recommended next activity
- `reasoning` (text, not null) — AI reasoning for the recommendation
- `estimated_duration` (integer, not null) — estimated minutes
- `adaptation_notes` (text, not null) — how plan adapted based on performance
- `day_number` (integer, not null) — which day this recommendation is for
- `trace_id` (text, nullable) — Neural Pulse trace ID for debugging
- `created_at` (timestamptz, default now())

## Security
- RLS enabled, single-tenant no-auth pattern (TO anon, authenticated, USING true)
- Consistent with existing tables

## Indexes
- `adaptive_plans.plan_id` — lookups by plan
- `adaptive_plans.created_at` — ordering by recency
*/

CREATE TABLE IF NOT EXISTS adaptive_plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  plan_id uuid NOT NULL REFERENCES study_plans(id) ON DELETE CASCADE,
  priority_topic text NOT NULL,
  recommended_activity text NOT NULL,
  reasoning text NOT NULL,
  estimated_duration integer NOT NULL,
  adaptation_notes text NOT NULL,
  day_number integer NOT NULL,
  trace_id text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE adaptive_plans ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_adaptive_plans" ON adaptive_plans;
CREATE POLICY "anon_select_adaptive_plans" ON adaptive_plans FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_adaptive_plans" ON adaptive_plans;
CREATE POLICY "anon_insert_adaptive_plans" ON adaptive_plans FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_adaptive_plans" ON adaptive_plans;
CREATE POLICY "anon_update_adaptive_plans" ON adaptive_plans FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_adaptive_plans" ON adaptive_plans;
CREATE POLICY "anon_delete_adaptive_plans" ON adaptive_plans FOR DELETE
  TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_adaptive_plans_plan_id ON adaptive_plans(plan_id);
CREATE INDEX IF NOT EXISTS idx_adaptive_plans_created_at ON adaptive_plans(created_at DESC);
